# Node that will host the workloads
nodeName: "sna-k8s"

# Namespace
namespace: "helm-v2x-stack"

# V2X Com values
name: "v2xcom1rsu"
labelTier: "far-edge"
labelRsu: "rsu"
image: "docker.io/pledger/v2xcom"
tag: "1.0"
imagePullPolicy: "Never"
port: "2395"
requestMemory: "6Mi"
requestCPU: "150m"
limitsMemory: "7Mi"
limitsCPU: "300m"
networkAttachmentDefinition: "macvlan-static-conf-vlan-2111-sna-k8s"
interface: "eth1"
command: "/rsu"
instanceName: "RSU_11p-1"
security: "none"

# MQTT Broker values (should match with the ones defined in the MQTT broker Helm Chart)
mqttBrokerService: "mqtt-broker-svc"
