# Namespace
namespace: "helm-v2x-stack"

# V2X Com values
name: "v2xcom1rsu"
labelNodeSelectorTier: "none"
labelNodeSelectorRsu: "none"
image: "docker.io/pledger/v2xcom"
tag: "1.0"
imagePullPolicy: "Never"
port: "2395"
requestMemory: "6Mi"
requestCPU: "150m"
limitsMemory: "7Mi"
limitsCPU: "300m"
networkAttachmentDefinition: "macvlan-static-conf-vlan-2111-sna-k8s"
interface: "eth1"
ip: "192.168.31.5/32"
command: "/rsu"
rsuName: "RSU_11p-1"
security: "none"

# MQTT Broker values (should match with the ones defined in the MQTT broker Helm Chart)
mqttbrokerService: "mqtt-broker-svc"
