# Node that will host the workloads
nodeName: "sna-k8s" 

# Namespace
namespace: "helm-v2x-stack"

#V2X Com values
v2xcom:
        name: "v2xcom1rsu"
        labelTier: "far-edge"
        labelRsu: "rsu"
        image: "docker.io/library/pledger/v2xcom"
        tag: "1.0"
        port: "2395"
        networkAttachmentDefinition: "macvlan-static-conf-vlan-31"
        interface: "eth1"
        ip: "192.168.31.5/32"
        rsuName: "RSU_11p-1"
        security: "none"

#MQTT Broker values
mqttbroker:
        service: "mqtt-broker-svc"

