# Node that will host the workloads
nodeName: "sna-k8s" 

# Namespace
namespace: "helm-v2x-stack"

#V2X Com values
v2xcom:
        name: "v2xcom1rsu"
        image: "docker.io/library/v2x-forwarder"
        tag: "latest"
        networkAttachmentDefinition: "macvlan-static-conf-vlan-31"
        interface: "eth1"
        ip: "192.168.31.5/32"
