apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}:{{.Values.tag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        ports:
        - containerPort: {{.Values.port}}
        resources:
          requests:
            memory: "{{.Values.requestMemory}}"
            cpu: "{{.Values.requestCPU}}"
          limits:
            memory: "{{.Values.limitsMemory}}"
            cpu: "{{.Values.limitsCPU}}"
      restartPolicy: Always
      nodeName: {{.Values.nodeName}}
