apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.name}}
  ports:
    - protocol: TCP
      port: {{.Values.port}}
      targetPort: {{.Values.port}}
