# Node that will host the workloads
nodeName: "sna-k8s"

# Namespace
namespace: "helm-v2x-stack"

# MQTT
name: "mqtt-broker"
image: "eclipse-mosquitto"
tag: "1.5"
imagePullPolicy: "Always"
port: "1883"
requestMemory: "6Mi"
requestCPU: "50m"
limitsMemory: "7Mi"
limitsCPU: "80m"
